<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllSorted()
	{
		return $this->getEntityManager()
		->createQuery('
				SELECT c FROM AppBundle:Category c
				ORDER BY c.name DESC
			')
		->getResult();
	}
}
